import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>welcome in next app</h1>
        <nav>
          <Link href="/home">home page</Link>
          <br />
          <Link href="/about">about page</Link>
          <br />
          <Link href="/contact">contact page</Link>
          <br />
          <Link href="/image">image page</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
